create extension if not exists pgcrypto;

create table if not exists tracked_products (
  id uuid primary key default gen_random_uuid(),
  store_product_id text not null unique,
  name text not null,
  url text not null,
  image_url text,
  created_at timestamptz not null default now(),
  active boolean not null default true
);

create table if not exists price_history (
  id bigint generated by default as identity primary key,
  tracked_product_id uuid not null references tracked_products(id) on delete cascade,
  price numeric(12,2) not null check (price >= 0),
  stock_status text not null check (stock_status in ('in_stock','out_of_stock','low_stock','unknown')),
  scraped_at timestamptz not null default now()
);

create index if not exists idx_price_history_product_time
  on price_history(tracked_product_id, scraped_at desc);

create table if not exists scrape_logs (
  id bigint generated by default as identity primary key,
  tracked_product_id uuid references tracked_products(id) on delete cascade,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  attempt integer not null,
  status text not null check (status in ('success','retried','failed')),
  http_status integer,
  error_message text,
  duration_ms integer,
  scraper_method text not null check (scraper_method in ('http','playwright')),
  metadata jsonb
);

create index if not exists idx_scrape_logs_product_time
  on scrape_logs(tracked_product_id, started_at desc);
